### ISSUE TITLE
error while loading shared libraries: libpcap.so.0.8

### ISSUE THREAD

**Issue by KayTaneJupiter** [broderickhyman/albiondata-client#100]
OpenSUSE Tumbleweed

Fails with "error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory"

Current version of libpcap is 1.0 +

OpenSUSE Tumbleweed on my machine provides:

/usr/lib64/libpcap.so.1
/usr/lib64/libpcap.so.1.10.1

 libpcap.so.0.8 is very old.

**Comment by KayTaneJupiter** [comment]
Problem remains in 0.1.5

**Comment by Aquinary** [comment]
I had the same problem on arch linux. I solved it like this:
`sudo ln -s /usr/lib/libpcap.so /usr/lib/libpcap.so.0.8`
Before doing this, check if you have libpcap.so at all
After that, everything worked for me

**Comment by KayTaneJupiter** [comment]
I'm trying to help the project fix their bugged software by reporting a bug. I'm not here to hack my own machine to work-around it for them. If they don't care about Linux users contributing data to albiondata, why should I?

**Comment by Aquinary** [comment]
You're using Linux. If you use linux, you should be ready to fuck this shit, break your system, and so on.
There are too many distributions to predict the behavior of each of them. If it's too hard for you, go back to Windows, there are no such problems there.

**Comment by KayTaneJupiter** [comment]
No. I use Linux instead of Windows precisely so I don't have to "fuck this shit" and "break your system". But this thread is already off-topic.

**Comment by Aquinary** [comment]
If you were on Windows, you would just run the program. The game, the app, Photoshop - it doesn't matter, it will work well. 
In linux, you need to fuck this well to make it work. It's inevitable. Either you get used to it and learn how to work with the terminal and the system, or you give up and don't think about Linux at all anymore. Everyone has been through this.
In the future, you will face even more problems and solving them is a necessary skill.
You also need to know that many programs developed by a group of people and they have no responsibility to you. You did not buy this program, so you use it "as is", if it does not work only for you (and this is not a global problem), then this is a problem specifically your system. 
If the window installer can't supply you with a window because you have solid stone walls, then that's your house's problem, not the window installer's.

I I don't know English very well, so the meaning of some phrases may not be translated correctly, I apologize in advance for this.

**Comment by richip** [comment]
Give permissions to set network device to promiscuous mode: `sudo setcap cap_net_raw,cap_net_admin=eip update-linux-amd64`

**Comment by willwh** [comment]
@richip I'm curious if you're interested in coming along for the ride....... I am just starting to cut my teeth on trying to build a copr repo for this....

For now, I've put this together: https://github.com/willwh/albiondata-client/blob/master/pkg/albiondata-client.spec - although my builds are failing, and it's time for bed for tonight. https://download.copr.fedorainfracloud.org/results/willwh/albiondata-client/fedora-rawhide-x86_64/04154146-albiondata-client/builder-live.log.gz

If you'd like to try this out on your local system, the following should work:

```
sudo dnf install rpm-build
git clone https://github.com/willwh/albiondata-client
spectool -g -R albiondata-client/pkg/albiondata-client.spec
rpmbuild -bs albiondata-client/pkg/albiondata-client.spec
sudo dnf install $HOME/rpmbuild/SRPMS/albiondata-client-0.1.7-0.src.rpm
```
Then you can just run with `albiondata-client`.

Once I figure out the failing builds..... you will be able to:

```
sudo dnf copr enable willwh/albiondata-client
sudo dnf install albiondata-client
```
