### ISSUE TITLE
Albion data client shuts down when I log into albion.

### ISSUE THREAD

**Issue by phenne** [broderickhyman/albiondata-client#58]
No logs available unfortunately.
Platform: Windows 10.

**Comment by oGamefreak** [comment]
Same issue here.

**Comment by Briack** [comment]
Try running the program as an administrator.

**Comment by Tyrben** [comment]
If it's a problem of WinPCap second use failure (like said in every other "shutdown issues", why not just resinstall it at every startup, automatically?
This is the only reason why I don't run "albiondata-client" all the time... because it crashes when it wasn't freshly reinstalled (I mean, WinPCap part)
